spring.application.name=rapidrent
# Portul pe care ruleaza aplicatia
server.port=8080

# Conexiunea la baza de date PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/rapidrent_db
spring.datasource.username=postgres
spring.datasource.password=user

# Hibernate: Creează automat tabelele în baza de date pe baza claselor noastre (User, Car, etc.)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Cheie secretă generată pentru JWT (trebuie să aibă cel puțin 256 biți / 32 caractere)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Timpul de expirare al token-ului în milisecunde (aici: 24 de ore)
jwt.expiration=86400000
# Populează automat baza de date goală cu conturi și mașini demo pentru prezentarea interfeței.
# Setează false dacă nu vrei date demo.
rapidrent.demo-data.enabled=true
